name: 💿 CI Branch

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-branch:
    name: 🏭 Build Branch
    runs-on: ubuntu-20.04
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@master
      - name: 🛠 Setup .NET Core
        uses: actions/setup-dotnet@master
      - name: ⚙ Restore
        run: dotnet restore
      - name: 🏭 Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: 🧪 Tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration
