name: 💿 CI Prod

on:
  push:
    tags:
      - "v*"

jobs:
  build-prod:
    name: 🏭 Build Prod
    runs-on: ubuntu-20.04
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@master
      - name: 🛠 Setup .NET Core
        uses: actions/setup-dotnet@master
      - name: ⚙ Restore
        run: dotnet restore
      - name: 🏭 Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: 🧪 Tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration
      - name: 🗜 Pack artifacts
        run: dotnet pack src -c Release --no-build -o artifacts/
      - name: 🗄 Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: 📦 Publish to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json
