group:
  - files:
      - source: main-workflows/
        dest: .github/workflows/
      - source: root/
        dest: ./
      - source: github/
        dest: .github/
    repos: |
      prom-client-net/prom-client
      prom-client-net/prom-client-dependencyinjection
      prom-client-net/prom-client-healthchecks
      prom-client-net/prom-client-httprequestdurations
      prom-client-net/prom-client-aspnetcore
      prom-client-net/prom-tmpl
      prom-client-net/prom-client-metricpusher
      prom-client-net/prom-client-metricserver

  - files:
      - source: simple-workflows/
        dest: .github/workflows/
    repos: |
      prom-client-net/prom-tmpl
      prom-client-net/prom-client-dependencyinjection
      prom-client-net/prom-client-httprequestdurations
      prom-client-net/prom-client-metricpusher
