name: ☣ Auto Merge
on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    name: 🛠 automerge
    runs-on: ubuntu-20.04
    steps:
      - name: ☢ automerge
        uses: pascalgn/automerge-action@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_RETRY_SLEEP: 15000
          MERGE_FORKS: false
          MERGE_RETRIES: "5"
