name: 💿 CI PR

on:
  pull_request:
    branches:
      - "master"

jobs:
  build-pr:
    name: 🏭 Build PR
    runs-on: ubuntu-20.04
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@master
      - name: 🛠 Setup .NET Core
        uses: actions/setup-dotnet@master
      - name: ⚙ Restore
        run: dotnet restore
      - name: 🏭 Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: 🧪 Run tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: ☢ Publish to Codecov
        uses: codecov/codecov-action@v2
