name: 💿 CI Prod

on:
  push:
    tags:
      - "v*"

jobs:
  build-prod:
    name: 🏭 Build Prod
    runs-on: ubuntu-20.04
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
      - name: 🛠 Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: ⚙ Restore
        run: dotnet restore
      - name: 🏭 Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: 🧪 Run tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: ☢ Publish to Codecov
        uses: codecov/codecov-action@v2
      - name: 🗜 Pack artifacts
        run: dotnet pack -c Release --no-build -o artifacts/
      - name: 🗄 Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: 📦 Publish to GitHub
        run: dotnet nuget push "artifacts/*.nupkg" -s https://nuget.pkg.github.com/prom-client-net/index.json -k ${{ secrets.GH_DEPLOY_KEY }} --skip-duplicate
      - name: 📦 Publish to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json
